### ISSUE TITLE
Sacred Flame deals no damage

### ISSUE THREAD

**Issue by diplomatNSTAR** [xxauroraxx/dnd5e#3]
When testing with other players, sacred flame didnt deal damage but appeared to have drained mana

**Comment by diplomatNSTAR** [comment]
Correction, all direct damage spells seem to be not working. Tested with inflict, magic missile and sacred flame

**Comment by aurorapar** [comment]
How were you testing this? Spells will not deal damage to allies.

I could successfully kill a bot with 2 casts of "!cast Inflict 50".

![image](https://user-images.githubusercontent.com/2294961/94644313-8bec0d00-02ae-11eb-8924-c0eea6e2fae0.png)

**Comment by aurorapar** [comment]
Spell Sacred Flame was indeed bugged. During development, I changed the `diceCheck` function to also need the attacker or caster of the spell passed in as the last argument. Sacred Flame was never updated to pass in all the arguments.

The target of Magic Missile was wrapped in the incorrect object. I extended the `player` object to add properties unique to D&D. The target was not using this extended object `RPGPlayer` and therefor damage may not have been rolled appropriately. 


In regards to Sacred Flame, I did a search to ensure other spells were passing in the correct number of parameters. I found several instances where that was not the case. Fixed in commit https://github.com/xxauroraxx/dnd5e/commit/27e9d6c34fa3e1b35a18744e7447403c7bb9ecdc
