### ISSUE TITLE
Spiritual Weapon returns error

### ISSUE THREAD

**Issue by diplomatNSTAR** [xxauroraxx/dnd5e#5]
] !cast Spiritual Weapon P2000
Bad format string in CLocalizeStringTable::ConstructString

**Comment by diplomatNSTAR** [comment]
looks to be a weapon name error, testing

**Comment by diplomatNSTAR** [comment]
verified that this is cause by the name of the gun, may need to handle bad weapon names

**Comment by aurorapar** [comment]
Caused by not enclosing your spell in quotes.

<code>
] rcon mp_restartgame 1
The game will restart in 1 second
] "!cast Spiritual Weapon test"
Unknown command: !cast Spiritual Weapon test
] "!cast Spiritual Weapon rawr"
Unknown command: !cast Spiritual Weapon rawr
] "!cast Spiritual Weapon weapon_negev"
Unknown command: !cast Spiritual Weapon weapon_negev
] bind mouse4 "!cast Spiritual Weapon negev"
] rcon mp_restartgame 1
The game will restart in 1 second
] "!cast Spiritual Weapon P2000"
Unknown command: !cast Spiritual Weapon P2000
Achievements disabled: cheats turned on in this app session.
] !cast Spiritual Weapon P2000
Bad format string in CLocalizeStringTable::ConstructString</code>
